openapi: 3.0.3
info:
  title: Cardápio SENAC API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

components:
  schemas:
    Link:
      type: object
      properties:
        href:
          type: string
        method:
          type: string
      required: [href]

    Links:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Link"

    Meta:
      type: object
      properties:
        correlationId:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
          required: [code, message]
        meta:
          $ref: "#/components/schemas/Meta"
      required: [error]
